### PR TITLE
Pyqt5 to pyqt6 migration

### PR DESCRIPTION
**Pull request by RaghavaAlajangi**
## Intro
This PR aims to migrate the codebase from pyqt5 to pyqt6
This is needed because QtCreator does not support PyQt5. It is explained in the issue #165.

### To do:
- [x] Refactor code to be adopted to pyqt6
- [ ] CI/CD pipeline passed
- [ ] Tests pass locally (run `pytest tests` on your computer)
- [x] update CHANGELOG

### CODE REVIEW

**Comment by paulmueller** [comment]
Thanks for this effort!
It riddles me that CI fails. For the linux runners, `apt install libgl1-mesa-glx` in the workflow might help, but for Windows and macOS I am not sure what happens. Can you run `python -m shapeout2 --version` from the terminal on your Windows machine? Maybe the `__main__` module needs refactoring.

I will be able to take a closer look in one or two weeks :+1:

**Comment by RaghavaAlajangi** [comment]
I get the below result when I run the command:
```
$ python -m shapeout2 --version
C:\Raghava_local\GITLAB\forks\ShapeOut2\shapeout2\__main__.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
0.0.post927+g3e770f4.d20241024
Segmentation fault


```

**Comment by paulmueller** [comment]
OK, then the culprit is somewhere inside the `__main__` module. You could try commenting things out or adding print statements to see where things go wrong.

**Comment by RaghavaAlajangi** [comment]
Hi Paul,
I ran the application without any arguments like:

changed the below line in `__main__`
```
# window = ShapeOut2(*app.arguments()[1:])

window = ShapeOut2()
```
In this case, it is working. I can open the files and sessions. But, when I run the tests, they still fail.

**Comment by RaghavaAlajangi** [comment]
Hi @paulmueller ,
I ran tests today without making any changes. Surprisingly, they were all passed.

**Comment by paulmueller** [comment]
The tests still fail. I narrowed it down to the instantiation of the AnalysisView class, which probably should be implemented via promotion in QtDesigner. I will merge your changes into a separate branch and work on it from there.

Thanks!

**Pull request merged**
